title: John Laudun
author: John Laudun
description   : 'portfolio of research and teaching activity'
slogan        : 'again the agon'
# email: your-email@domain.com

plugins:
  # - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  # - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
- posts.md
- github.md

footer_icons:
- username: johnlaudun
  url: https://github.com/johnlaudun/
  icon: icon-github.svg

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
